// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/bank/type/exchange.proto

package bank

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=fromCurrency,json=from_currency,proto3" json:"fromCurrency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=toCurrency,json=from_currency,proto3" json:"toCurrency,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,json=from_currency,proto3" json:"rate,omitempty"`
	ValidFrom     *date.Date             `protobuf:"bytes,4,opt,name=validFrom,json=valid_from,proto3" json:"validFrom,omitempty"`
	ValidTo       *date.Date             `protobuf:"bytes,5,opt,name=validTo,json=valid_to,proto3" json:"validTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExchangeRateRequest) Reset() {
	*x = CreateExchangeRateRequest{}
	mi := &file_proto_bank_type_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeRateRequest) ProtoMessage() {}

func (x *CreateExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*CreateExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExchangeRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *CreateExchangeRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *CreateExchangeRateRequest) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *CreateExchangeRateRequest) GetValidFrom() *date.Date {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *CreateExchangeRateRequest) GetValidTo() *date.Date {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

type CreateExchangeRateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExchangeRateUUID string                 `protobuf:"bytes,1,opt,name=exchangeRateUUID,json=exchange_rate_uuid,proto3" json:"exchangeRateUUID,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateExchangeRateResponse) Reset() {
	*x = CreateExchangeRateResponse{}
	mi := &file_proto_bank_type_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeRateResponse) ProtoMessage() {}

func (x *CreateExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*CreateExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExchangeRateResponse) GetExchangeRateUUID() string {
	if x != nil {
		return x.ExchangeRateUUID
	}
	return ""
}

type ExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=fromCurrency,json=from_currency,proto3" json:"fromCurrency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=toCurrency,json=to_currency,proto3" json:"toCurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateRequest) Reset() {
	*x = ExchangeRateRequest{}
	mi := &file_proto_bank_type_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateRequest) ProtoMessage() {}

func (x *ExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type ExchangeRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=fromCurrency,json=from_currency,proto3" json:"fromCurrency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=toCurrency,json=to_currency,proto3" json:"toCurrency,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateResponse) Reset() {
	*x = ExchangeRateResponse{}
	mi := &file_proto_bank_type_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateResponse) ProtoMessage() {}

func (x *ExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*ExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeRateResponse) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRateResponse) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ExchangeRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ExchangeRateResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_bank_type_exchange_proto protoreflect.FileDescriptor

const file_proto_bank_type_exchange_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/bank/type/exchange.proto\x12\x04bank\x1a\x17proto/google/date.proto\"\xe0\x01\n" +
	"\x19CreateExchangeRateRequest\x12#\n" +
	"\ffromCurrency\x18\x01 \x01(\tR\rfrom_currency\x12!\n" +
	"\n" +
	"toCurrency\x18\x02 \x01(\tR\rfrom_currency\x12\x1b\n" +
	"\x04rate\x18\x03 \x01(\x01R\rfrom_currency\x120\n" +
	"\tvalidFrom\x18\x04 \x01(\v2\x11.google.type.DateR\n" +
	"valid_from\x12,\n" +
	"\avalidTo\x18\x05 \x01(\v2\x11.google.type.DateR\bvalid_to\"J\n" +
	"\x1aCreateExchangeRateResponse\x12,\n" +
	"\x10exchangeRateUUID\x18\x01 \x01(\tR\x12exchange_rate_uuid\"[\n" +
	"\x13ExchangeRateRequest\x12#\n" +
	"\ffromCurrency\x18\x01 \x01(\tR\rfrom_currency\x12\x1f\n" +
	"\n" +
	"toCurrency\x18\x02 \x01(\tR\vto_currency\"\x8e\x01\n" +
	"\x14ExchangeRateResponse\x12#\n" +
	"\ffromCurrency\x18\x01 \x01(\tR\rfrom_currency\x12\x1f\n" +
	"\n" +
	"toCurrency\x18\x02 \x01(\tR\vto_currency\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestampB2Z0github.com/danielgom/grpc-proto/protogen/go/bankb\x06proto3"

var (
	file_proto_bank_type_exchange_proto_rawDescOnce sync.Once
	file_proto_bank_type_exchange_proto_rawDescData []byte
)

func file_proto_bank_type_exchange_proto_rawDescGZIP() []byte {
	file_proto_bank_type_exchange_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_exchange_proto_rawDesc), len(file_proto_bank_type_exchange_proto_rawDesc)))
	})
	return file_proto_bank_type_exchange_proto_rawDescData
}

var file_proto_bank_type_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_bank_type_exchange_proto_goTypes = []any{
	(*CreateExchangeRateRequest)(nil),  // 0: bank.CreateExchangeRateRequest
	(*CreateExchangeRateResponse)(nil), // 1: bank.CreateExchangeRateResponse
	(*ExchangeRateRequest)(nil),        // 2: bank.ExchangeRateRequest
	(*ExchangeRateResponse)(nil),       // 3: bank.ExchangeRateResponse
	(*date.Date)(nil),                  // 4: google.type.Date
}
var file_proto_bank_type_exchange_proto_depIdxs = []int32{
	4, // 0: bank.CreateExchangeRateRequest.validFrom:type_name -> google.type.Date
	4, // 1: bank.CreateExchangeRateRequest.validTo:type_name -> google.type.Date
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_bank_type_exchange_proto_init() }
func file_proto_bank_type_exchange_proto_init() {
	if File_proto_bank_type_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_exchange_proto_rawDesc), len(file_proto_bank_type_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_exchange_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_exchange_proto_depIdxs,
		MessageInfos:      file_proto_bank_type_exchange_proto_msgTypes,
	}.Build()
	File_proto_bank_type_exchange_proto = out.File
	file_proto_bank_type_exchange_proto_goTypes = nil
	file_proto_bank_type_exchange_proto_depIdxs = nil
}
