// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/bank/service.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_bank_service_proto protoreflect.FileDescriptor

const file_proto_bank_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/bank/service.proto\x12\x04bank\x1a\x1dproto/bank/type/account.proto\x1a\x1eproto/bank/type/exchange.proto\x1a!proto/bank/type/transaction.proto2\xa5\x03\n" +
	"\vBankService\x12H\n" +
	"\rCreateAccount\x12\x1a.bank.CreateAccountRequest\x1a\x1b.bank.CreateAccountResponse\x12N\n" +
	"\x11GetCurrentBalance\x12\x1b.bank.CurrentBalanceRequest\x1a\x1c.bank.CurrentBalanceResponse\x12W\n" +
	"\x12CreateExchangeRate\x12\x1f.bank.CreateExchangeRateRequest\x1a .bank.CreateExchangeRateResponse\x12L\n" +
	"\x11FetchExchangeRate\x12\x19.bank.ExchangeRateRequest\x1a\x1a.bank.ExchangeRateResponse0\x01\x12U\n" +
	"\x15SummarizeTransactions\x12\x18.bank.TransactionRequest\x1a .bank.TransactionSummaryResponse(\x01B2Z0github.com/danielgom/grpc-proto/protogen/go/bankb\x06proto3"

var file_proto_bank_service_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),       // 0: bank.CreateAccountRequest
	(*CurrentBalanceRequest)(nil),      // 1: bank.CurrentBalanceRequest
	(*CreateExchangeRateRequest)(nil),  // 2: bank.CreateExchangeRateRequest
	(*ExchangeRateRequest)(nil),        // 3: bank.ExchangeRateRequest
	(*TransactionRequest)(nil),         // 4: bank.TransactionRequest
	(*CreateAccountResponse)(nil),      // 5: bank.CreateAccountResponse
	(*CurrentBalanceResponse)(nil),     // 6: bank.CurrentBalanceResponse
	(*CreateExchangeRateResponse)(nil), // 7: bank.CreateExchangeRateResponse
	(*ExchangeRateResponse)(nil),       // 8: bank.ExchangeRateResponse
	(*TransactionSummaryResponse)(nil), // 9: bank.TransactionSummaryResponse
}
var file_proto_bank_service_proto_depIdxs = []int32{
	0, // 0: bank.BankService.CreateAccount:input_type -> bank.CreateAccountRequest
	1, // 1: bank.BankService.GetCurrentBalance:input_type -> bank.CurrentBalanceRequest
	2, // 2: bank.BankService.CreateExchangeRate:input_type -> bank.CreateExchangeRateRequest
	3, // 3: bank.BankService.FetchExchangeRate:input_type -> bank.ExchangeRateRequest
	4, // 4: bank.BankService.SummarizeTransactions:input_type -> bank.TransactionRequest
	5, // 5: bank.BankService.CreateAccount:output_type -> bank.CreateAccountResponse
	6, // 6: bank.BankService.GetCurrentBalance:output_type -> bank.CurrentBalanceResponse
	7, // 7: bank.BankService.CreateExchangeRate:output_type -> bank.CreateExchangeRateResponse
	8, // 8: bank.BankService.FetchExchangeRate:output_type -> bank.ExchangeRateResponse
	9, // 9: bank.BankService.SummarizeTransactions:output_type -> bank.TransactionSummaryResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bank_service_proto_init() }
func file_proto_bank_service_proto_init() {
	if File_proto_bank_service_proto != nil {
		return
	}
	file_proto_bank_type_account_proto_init()
	file_proto_bank_type_exchange_proto_init()
	file_proto_bank_type_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_service_proto_rawDesc), len(file_proto_bank_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bank_service_proto_goTypes,
		DependencyIndexes: file_proto_bank_service_proto_depIdxs,
	}.Build()
	File_proto_bank_service_proto = out.File
	file_proto_bank_service_proto_goTypes = nil
	file_proto_bank_service_proto_depIdxs = nil
}
