// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/bank/type/transaction.proto

package bank

import (
	_ "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_TRANSACTION_TYPE_IN          TransactionType = 1
	TransactionType_TRANSACTION_TYPE_OUT         TransactionType = 2
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_IN",
		2: "TRANSACTION_TYPE_OUT",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION_TYPE_IN":          1,
		"TRANSACTION_TYPE_OUT":         2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bank_type_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_bank_type_transaction_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bank_type_transaction_proto_rawDescGZIP(), []int{0}
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=accountNumber,json=account_number,proto3" json:"accountNumber,omitempty"`
	Type          TransactionType        `protobuf:"varint,2,opt,name=type,proto3,enum=bank.TransactionType" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Notes         string                 `protobuf:"bytes,16,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_proto_bank_type_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *TransactionRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *TransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type TransactionSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=accountNumber,json=account_number,proto3" json:"accountNumber,omitempty"`
	AmountIn      float64                `protobuf:"fixed64,2,opt,name=amountIn,json=amount_in,proto3" json:"amountIn,omitempty"`
	AmountOut     float64                `protobuf:"fixed64,3,opt,name=amountOut,json=amount_out,proto3" json:"amountOut,omitempty"`
	SumTotal      float64                `protobuf:"fixed64,4,opt,name=sumTotal,proto3" json:"sumTotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionSummaryResponse) Reset() {
	*x = TransactionSummaryResponse{}
	mi := &file_proto_bank_type_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSummaryResponse) ProtoMessage() {}

func (x *TransactionSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSummaryResponse.ProtoReflect.Descriptor instead.
func (*TransactionSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionSummaryResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *TransactionSummaryResponse) GetAmountIn() float64 {
	if x != nil {
		return x.AmountIn
	}
	return 0
}

func (x *TransactionSummaryResponse) GetAmountOut() float64 {
	if x != nil {
		return x.AmountOut
	}
	return 0
}

func (x *TransactionSummaryResponse) GetSumTotal() float64 {
	if x != nil {
		return x.SumTotal
	}
	return 0
}

var File_proto_bank_type_transaction_proto protoreflect.FileDescriptor

const file_proto_bank_type_transaction_proto_rawDesc = "" +
	"\n" +
	"!proto/bank/type/transaction.proto\x12\x04bank\x1a\x17proto/google/date.proto\"\x94\x01\n" +
	"\x12TransactionRequest\x12%\n" +
	"\raccountNumber\x18\x01 \x01(\tR\x0eaccount_number\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.bank.TransactionTypeR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05notes\x18\x10 \x01(\tR\x05notes\"\x9b\x01\n" +
	"\x1aTransactionSummaryResponse\x12%\n" +
	"\raccountNumber\x18\x01 \x01(\tR\x0eaccount_number\x12\x1b\n" +
	"\bamountIn\x18\x02 \x01(\x01R\tamount_in\x12\x1d\n" +
	"\tamountOut\x18\x03 \x01(\x01R\n" +
	"amount_out\x12\x1a\n" +
	"\bsumTotal\x18\x04 \x01(\x01R\bsumTotal*f\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRANSACTION_TYPE_IN\x10\x01\x12\x18\n" +
	"\x14TRANSACTION_TYPE_OUT\x10\x02B2Z0github.com/danielgom/grpc-proto/protogen/go/bankb\x06proto3"

var (
	file_proto_bank_type_transaction_proto_rawDescOnce sync.Once
	file_proto_bank_type_transaction_proto_rawDescData []byte
)

func file_proto_bank_type_transaction_proto_rawDescGZIP() []byte {
	file_proto_bank_type_transaction_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_transaction_proto_rawDesc), len(file_proto_bank_type_transaction_proto_rawDesc)))
	})
	return file_proto_bank_type_transaction_proto_rawDescData
}

var file_proto_bank_type_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_bank_type_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bank_type_transaction_proto_goTypes = []any{
	(TransactionType)(0),               // 0: bank.TransactionType
	(*TransactionRequest)(nil),         // 1: bank.TransactionRequest
	(*TransactionSummaryResponse)(nil), // 2: bank.TransactionSummaryResponse
}
var file_proto_bank_type_transaction_proto_depIdxs = []int32{
	0, // 0: bank.TransactionRequest.type:type_name -> bank.TransactionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bank_type_transaction_proto_init() }
func file_proto_bank_type_transaction_proto_init() {
	if File_proto_bank_type_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_transaction_proto_rawDesc), len(file_proto_bank_type_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_transaction_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_transaction_proto_depIdxs,
		EnumInfos:         file_proto_bank_type_transaction_proto_enumTypes,
		MessageInfos:      file_proto_bank_type_transaction_proto_msgTypes,
	}.Build()
	File_proto_bank_type_transaction_proto = out.File
	file_proto_bank_type_transaction_proto_goTypes = nil
	file_proto_bank_type_transaction_proto_depIdxs = nil
}
